version: '3.7'
services:
  ##Postgres Item
  postgres-rimba-item:
    container_name: postgres-rimba-item
    image: postgres:latest
    volumes:
      - ./docker-compose-config/postgres-rimba-item:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: item_rimba
      POSTGRES_USER: rimba
      POSTGRES_PASSWORD: rimba123
      PGDATA: /data/postgres
    restart: always
    networks:
      - rimba

  ##Postgres Customer
  postgres-rimba-customer:
    container_name: postgres-rimba-customer
    image: postgres:latest
    volumes:
      - ./docker-compose-config/postgres-rimba-customer:/data/postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: customer_rimba
      POSTGRES_USER: rimba
      POSTGRES_PASSWORD: rimba123
      PGDATA: /data/postgres
    restart: always
    networks:
      - rimba

  ##Postgres Sales
  postgres-rimba-sales:
    container_name: postgres-rimba-sales
    image: postgres:latest
    volumes:
      - ./docker-compose-config/postgres-rimba-sales:/data/postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: sales_rimba
      POSTGRES_USER: rimba
      POSTGRES_PASSWORD: rimba123
      PGDATA: /data/postgres
    restart: always
    networks:
      - rimba

  ## Item service
  item-service:
    container_name: item-service
    build:
      context: ./item-service
      dockerfile: Dockerfile
    pull_policy: always
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:postgresql://postgres-rimba-item:5432/item_rimba",
                "spring.datasource.username" : "rimba",
                "spring.datasource.password" : "rimba123"
              }'

    networks:
      - rimba
    depends_on:
      - postgres-rimba-item

  ## Customer service
  customer-service:
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    pull_policy: always
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:postgresql://postgres-rimba-customer:5432/customer_rimba",
                "spring.datasource.username" : "rimba",
                "spring.datasource.password" : "rimba123"
              }'
    networks:
      - rimba
    depends_on:
      - postgres-rimba-customer

  ## Sales service
  sales-service:
    container_name: sales-service
    build:
      context: ./sales-service
      dockerfile: Dockerfile
    pull_policy: always
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:postgresql://postgres-rimba-sales:5432/sales_rimba",
                "spring.datasource.username" : "rimba",
                "spring.datasource.password" : "rimba123"
              }'
    networks:
      - rimba
    depends_on:
      - postgres-rimba-sales

  ## Nginx Api Gateway
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rimba
    depends_on:
      - postgres-rimba-item
      - postgres-rimba-customer
      - postgres-rimba-sales
      - item-service
      - customer-service
      - sales-service

networks:
  rimba:
    driver: bridge